version: '1.0.{build}'

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MY_VS_VERSION: Visual Studio 14 2015 Win64
      MY_VS_SHORT: VS2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      MY_VS_VERSION: Visual Studio 15 2017 Win64
      MY_VS_SHORT: VS2017

branches:
  except:
    - gh-pages
 
platform:
  - x64
 
configuration:
  - Release
  - Debug

before_build:
  - cmake -G "%MY_VS_VERSION%" .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\SyDEVS.sln     # path to Visual Studio solution or project
  parallel: true                                   # enable MSBuild parallel builds
  verbosity: normal                                # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  - cd c:\projects\sydevs
  - if "%APPVEYOR_REPO_TAG%"=="true" (set CONTENT_NAME=sydevs-%APPVEYOR_REPO_TAG_NAME%) else (set CONTENT_NAME=sydevs-%APPVEYOR_REPO_COMMIT%)
  - mkdir %CONTENT_NAME% %CONTENT_NAME%\lib %CONTENT_NAME%\include %CONTENT_NAME%\include\sydevs %CONTENT_NAME%\include\sydevs\systems %CONTENT_NAME%\include\sydevs\time %CONTENT_NAME%\include\sydevs\core
  - copy src\sydevs\core\*.h %CONTENT_NAME%\include\sydevs\core
  - copy src\sydevs\systems\*.h %CONTENT_NAME%\include\sydevs\systems
  - copy src\sydevs\time\*.h %CONTENT_NAME%\include\sydevs\time
  - copy %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\SyDEVS*.* %CONTENT_NAME%\lib
  - copy LICENSE.md %CONTENT_NAME%
  - if "%APPVEYOR_REPO_TAG%"=="true" (set ARCHIVE_NAME=SyDEVS-%APPVEYOR_REPO_TAG_NAME%_Win64_%MY_VS_SHORT%_%CONFIGURATION%) else (set ARCHIVE_NAME=SyDEVS-%APPVEYOR_REPO_COMMIT%_Win64_%MY_VS_SHORT%_%CONFIGURATION%)
  - 7z a %ARCHIVE_NAME%.zip %CONTENT_NAME%
  - appveyor PushArtifact %ARCHIVE_NAME%.zip

deploy:
  - provider: Environment
    name: SyDEVS-Releases
    artifact: $(ARCHIVE_NAME).zip
    force_update: true
    on:
      appveyor_repo_tag: true
 