name: Build and Deploy SyDEVS

on:
  push:
  pull_request:
    branches:
      - Rasheedat/ci

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        vs-version: [2015, 2017]
        configuration: [Release, Debug]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version (v3)

    - name: Set up Visual Studio
      run: |
        if [ ${{ matrix.vs-version }} == 2015 ]; then
          vs_version="Visual Studio 14 2015 Win64"
          vs_short="VS2015"
        elif [ ${{ matrix.vs-version }} == 2017 ]; then
          vs_version="Visual Studio 15 2017 Win64"
          vs_short="VS2017"
        fi

    - name: Install CMake
      uses: actions/setup-cmake@v3  # Updated to the latest version (v3)
      with:
        cmake-version: '3.22'

    - name: Configure CMake
      run: |
        cmake -G "${vs_version}" .

    - name: Build with MSBuild
      run: |
        msbuild "$(AppVeyor.BuildFolder)\SyDEVS.sln" /p:Configuration=${{ matrix.configuration }} /m

    - name: Create content folder and copy files
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/"* ]]; then
          TAG_NAME="${GITHUB_REF##*/}"
          CONTENT_NAME="sydevs-${TAG_NAME}"
        else
          COMMIT="${GITHUB_SHA}"
          CONTENT_NAME="sydevs-${COMMIT}"
        fi
        mkdir "%CONTENT_NAME%" "%CONTENT_NAME%\lib" "%CONTENT_NAME%\include" "%CONTENT_NAME%\include\sydevs" "%CONTENT_NAME%\include\sydevs\systems" "%CONTENT_NAME%\include\sydevs\time" "%CONTENT_NAME%\include\sydevs\core"
        copy src\sydevs\core\*.h "%CONTENT_NAME%\include\sydevs\core"
        copy src\sydevs\systems\*.h "%CONTENT_NAME%\include\sydevs\systems"
        copy src\sydevs\time\*.h "%CONTENT_NAME%\include\sydevs\time"
        copy "$(AppVeyor.BuildFolder)\${{ matrix.configuration }}\SyDEVS*.*" "%CONTENT_NAME%\lib"
        copy LICENSE.md "%CONTENT_NAME%"

    - name: Create ZIP archive
      run: |
        if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/tags/"* ]]; then
          TAG_NAME="${GITHUB_REF##*/}"
          ARCHIVE_NAME="SyDEVS-${TAG_NAME}_Win64_${{ matrix.vs-short }}_${{ matrix.configuration }}"
        else
          COMMIT="${GITHUB_SHA}"
          ARCHIVE_NAME="SyDEVS-${COMMIT}_Win64_${{ matrix.vs-short }}_${{ matrix.configuration }}"
        fi
        7z a "${ARCHIVE_NAME}.zip" "%CONTENT_NAME%"

    - name: Upload artifact to GitHub
      uses: actions/upload-artifact@v3  # Updated to the latest version (v3)
      with:
        name: ${{ steps.create-archive.outputs.archive-name }}
        path: ${{ steps.create-archive.outputs.archive-path }}

  deploy:
    needs: build
    runs-on: windows-latest
    if: github.ref == 'refs/tags/*'
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3  # Updated to the latest version (v3)
      with:
        name: ${{ needs.build.outputs.archive-name }}
        path: .

    - name: Deploy to SyDEVS-Releases
      run: |
        # Example deployment steps
        echo "Deploying ${ARCHIVE_NAME} to SyDEVS-Releases..."
        # Add your deployment script here
