name: Build and Deploy SyDEVS

on:
  push:
  pull_request:
    branches:
      - Rasheedat/ci
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # Supported operating systems
        compiler: [gcc-12, clang-14]      # Compiler options
        configuration: ['Release', 'Debug']

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install dependencies for Ubuntu
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y software-properties-common
        if [[ "${{ matrix.compiler }}" == "gcc-12" ]]; then
          sudo apt-get install -y g++-12
          export CC=gcc-12
          export CXX=g++-12
        elif [[ "${{ matrix.compiler }}" == "clang-14" ]]; then
          sudo apt-get install -y clang-14 libc++-14-dev libc++abi-14-dev
          export CC=clang-14
          export CXX=clang++-14
        fi
        sudo apt-get install -y cmake

    # Install dependencies for macOS
    - name: Install dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        xcode-select --install || true  # Install Xcode command line tools
        brew install cmake  # Ensure CMake is installed
        cmake --version  # Verify installation

    # Configure and Build
    - name: Configure with CMake
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

    - name: Build project
      run: |
        cd build
        make

    # Archive artifacts
    - name: Archive artifacts
      run: |
        mkdir -p artifacts/lib artifacts/include/sydevs/core artifacts/include/sydevs/systems artifacts/include/sydevs/time
        if [[ -d src/sydevs/core ]]; then
          cp src/sydevs/core/*.h artifacts/include/sydevs/core || true
        fi
        if [[ -d src/sydevs/systems ]]; then
          cp src/sydevs/systems/*.h artifacts/include/sydevs/systems || true
        fi
        if [[ -d src/sydevs/time ]]; then
          cp src/sydevs/time/*.h artifacts/include/sydevs/time || true
        fi
        zip -r artifacts.zip artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: artifacts.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest  # Only Ubuntu is used for release job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Release
      run: |
        TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -X POST \
        -d '{"tag_name": "$TAG_NAME", "target_commitish": "main", "name": "Release $TAG_NAME", "body": "Release for version $TAG_NAME", "draft": false, "prerelease": false}' \
        https://api.github.com/repos/${{ github.repository }}/releases
