name: Build and Deploy

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Test on Ubuntu

    strategy:
      matrix:
        cc: [gcc-12, clang-14]  # Using a more recent version of gcc and clang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up CMake
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]]; then
          mkdir cmake-download && cd cmake-download &&
          curl -O https://cmake.org/files/v3.10/cmake-3.10.0-rc5-Linux-x86_64.sh &&
          bash cmake-3.10.0-rc5-Linux-x86_64.sh --skip-license &&
          cd ..
        fi

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        sudo apt update
        sudo apt install -y g++-12
        sudo apt install -y clang-14 libc++-dev doxygen graphviz

    - name: Set environment for CMake
      run: |
        mkdir build
        cd build
        cmake ..
        cd /home/runner/work/sydevs/sydevs/build

    - name: Build project
      run: |
        if [[ "${DOCUMENTATION}" == "true" ]]; then
          cd .. &&
          (cat doxygen.config; echo "PROJECT_NUMBER=${GITHUB_REF##*/}") | doxygen -
        fi

    - name: Archive and deploy
      run: |
        mkdir -p release/lib release/include/sydevs/core release/include/sydevs/systems release/include/sydevs/time
            cp src/sydevs/core/*.h release/include/sydevs/core
            cp src/sydevs/systems/*.h release/include/sydevs/systems
            cp src/sydevs/time/*.h release/include/sydevs/time
            cp LICENSE.md release/
            zip -r SyDEVS-${{ github.ref_name }}-${{ runner.os }}-${{ matrix.cc }}.zip release/
